language: rust

cache: cargo

os:
  - linux
  - osx

rust:
#  - stable
#  - beta
  - nightly

matrix:
  allow_failures:
    - rust:
      - stable
      - beta

language: rust
script:
  - cargo install -f clippy
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy
